# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 09:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='author',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
